### ISSUE TITLE
Issue to run bot via hosting

### ISSUE THREAD

**Issue by Spicydink** [Burhan-Q/Ultralytics_DiscordBot#51]
Here is error i got
 
File "/home/container/src/bot.py", line 252, in <module>
    main()
  File "/home/container/src/bot.py", line 19, in main
    _ = docs_choices(True) # Stores information locally for client to load
        ^^^^^^^^^^^^^^^^^^
  File "/home/container/src/UltralyticsBot/utils/docs_data.py", line 155, in docs_choices
    assert any(docs_idx), f"Unable to locate mkdocs index file in {into_path.as_posix()} repo directory."
AssertionError: Unable to locate mkdocs index file in /home/container/repo_data/ultralytics repo directory.

Traceback (most recent call last):
  File "/home/container/src/bot.py", line 252, in <module>
    main()
  File "/home/container/src/bot.py", line 19, in main
    _ = docs_choices(True) # Stores information locally for client to load
        ^^^^^^^^^^^^^^^^^^
  File "/home/container/src/UltralyticsBot/utils/docs_data.py", line 155, in docs_choices
    assert any(docs_idx), f"Unable to locate mkdocs index file in {into_path.as_posix()} repo directory."
AssertionError: Unable to locate mkdocs index file in /home/container/repo_data/ultralytics repo directory.

**Comment by Burhan-Q** [comment]
@Spicydink thanks for opening an issue and checking out the repo. I had made some changes that had not been merged into the main branch, but I just added them in #52 so if you `pull` the latest version, that issue should no longer happen. I have this build running presently in the Ultralytics Discord <a href="https://ultralytics.com/discord"><img alt="Discord" src="https://img.shields.io/discord/1089800235347353640?logo=discord&logoColor=white&label=Discord&color=blue"></a>

Right now there's a 15 day wait period after joining the server to get access to the bot. This was done primarily to let me test the bot without too many users trying it at once and to prevent abuse. Let me know if you have any other questions and please do share (here or in the Ultralytics Discord #show-n-tell channel) what you build!
